"""Column admin removed, not necessary

Revision ID: 6d292b86655b
Revises: 09964819e371
Create Date: 2025-09-28 12:41:47.634150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d292b86655b'
down_revision: Union[str, Sequence[str], None] = '09964819e371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'occupation',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    op.alter_column('users', 'occupation',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
